// This js file is not deferred.
// Must wait for window load or a similar event before trying to access these.
// Use relative paths. Do not use absolute reference to root with "/" as it could be uncertain what the root is in case of deep-iframing for domain masking.
var indexOfLessons = { // ONLY USED IN js_for_the_sliding_navigation_menu.js
  title:[ "💬",
          "🍞", // &#127838;
          "💧💦",
          "🍷📥",
          "🍞📤",
          "✋", /*NOTE: 1-1-5 is actually not a lesson. It is only a notification*/
          "1-2-1",
          "1-2-2",
          "1-2-3",
          "1-2-4",
          "1-3-1",
          "1-3-2",
          "1-3-3",
          "1-3-4",
          "1-4-1",
          "1-4-2",
          "1-4-3",
          "1-5-1",
          "1-5-2",
          "1-5-3",
          "1-6-1",
          "1-6-2",
          "1-6-3",
          "1-7-1",
          "1-7-2",
          "🏁" // &#127937;
          // The last one is “Want more content? We are working on it!” screen.
        ],
  path: [ "/user_interface/blank.html",
          "/lessons_in_iframes/level_1/unit_1/lesson_1/index.html",
          "/lessons_in_iframes/level_1/unit_1/lesson_2/index.html",
          "/lessons_in_iframes/level_1/unit_1/lesson_3/index.html",
          "/lessons_in_iframes/level_1/unit_1/lesson_4/index.html",
          "/lessons_in_iframes/level_1/unit_1/notice_0/index.html",
          "/lessons_in_iframes/level_1/unit_2/lesson_1/index.html",
          "/lessons_in_iframes/level_1/unit_2/lesson_2/index.html",
          "/lessons_in_iframes/level_1/unit_2/lesson_3/index.html",
          "/lessons_in_iframes/level_1/unit_2/lesson_4/index.html",
          "/lessons_in_iframes/level_1/unit_3/lesson_1/index.html",
          "/lessons_in_iframes/level_1/unit_3/lesson_2/index.html",
          "/lessons_in_iframes/level_1/unit_3/lesson_3/index.html",
          "/lessons_in_iframes/level_1/unit_3/lesson_4/index.html",
          "/lessons_in_iframes/level_1/unit_4/lesson_1/index.html",
          "/lessons_in_iframes/level_1/unit_4/lesson_2/index.html",
          "/lessons_in_iframes/level_1/unit_4/lesson_3/index.html",
          "/lessons_in_iframes/level_1/unit_5/lesson_1/index.html",
          "/lessons_in_iframes/level_1/unit_5/lesson_2/index.html",
          "/lessons_in_iframes/level_1/unit_5/lesson_3/index.html",
          "/lessons_in_iframes/level_1/unit_6/lesson_1/index.html",
          "/lessons_in_iframes/level_1/unit_6/lesson_2/index.html",
          "/lessons_in_iframes/level_1/unit_6/lesson_3/index.html",
          "/lessons_in_iframes/level_1/unit_7/lesson_1/index.html",
          "/lessons_in_iframes/level_1/unit_7/lesson_2/index.html",
          "/lessons_in_iframes/level_1/unit_7/lesson_3/index.html"
        ]
};
